// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://uzfluvtiezeszlxkogm2a4l7kq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:a631ae37-6fab-46d5-ac9d-f76503d81cf7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mAXw64q4s",
    "aws_user_pools_web_client_id": "7023mc8m52spi3aklq04n8u2be",
    "oauth": {
        "domain": "mysvelteprojectaa3cccfd-aa3cccfd-tempwodijw.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8080/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
